[mypy]
python_version = 3.11
ignore_missing_imports = True
follow_imports = skip
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_incomplete_defs = True
exclude = (tests/|examples/|tools/|setup_dev|manual_test|test_all_models)
